title:              Batuhan Yildirim
email:              by256@cam.ac.uk
# description:        A Blog Theme by Start Bootstrap
author:             Batuhan Yildirim
baseurl:            ""
url:                "https://by256.github.io/"

# Social Profiles
twitter_username:   batuhanyil
github_username:    by256
linkedin_username:  batuhanyildirim

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: pygments
permalink: pretty
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
