title: Batuhan Yildirim
repository: by256/by256.github.io
url: https://by256.github.io/

# Setup
highlighter: rouge
markdown:    kramdown
strict_front_matter: true


# Build
paginate: 6
permalink: /:slug-:short_year:month:day
profile: true

# Dev
livereload: true
host: 0.0.0.0

author:
    name: Batuhan Yildirim
    email: by256(AT)cam.ac.uk
    blog: https://by256.github.io

    social:
        github:
            link: https://github.com/by256
            text: GitHub

        linkedin:
            link: https://www.linkedin.com/in/batuhanyildirim/
            text: LinkedIn

        twitter:
            link: https://twitter.com/batuhanyil
            text: Twitter
